spring.application.name=medical-record

spring.datasource.url=jdbc:mariadb://money-me.cvw6ya0iut7u.eu-north-1.rds.amazonaws.com:3306/medical_record
spring.datasource.username=admin
spring.datasource.password=VW1emxOsa3rxFJVe9bcA
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=DEBUG

#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.settings=true

#aA123123!
